load ../evoluce/evolution.maude
load ./colored_result.maude

fmod TESTSUITE is
	pr COLORING .
	pr ORMSYSTEM .
endfm

--- ADDCLASS : Class OrmSystem -> OrmSystem .
red test(addClass(class('Q, [], [], []), system(application([], []), database([],[]) )) == system(application(class('Q, [], [], []), []), database(table('Q, primaryKey('Id), [], []), []))) .
red test(addClass(class('Q, [], [], []), system(application(class('Q, [], [], []), []), database([],[]) )) == system(errApplication("add class - the name already exists", application(class('Q, [], [], []), [])), database(table('Q, primaryKey('Id), [], []), []))) .
red test(addClass(class('Q, [], [], []), system(application([], []), database(table('Q, primaryKey('Id), [], []), []))) == system(application(class('Q, [], [], []), []), errDatabase("add table - name exists", database(table('Q, primaryKey('Id), [], []), [])))) .
--- with primitiveCollections
red test(addClass(class('Q, [],  primitiveCollection('strings, APP-STRING, "value", true), []), system(application([], []), database([],[]) )) == system(application(class('Q, [], primitiveCollection('strings, APP-STRING, "value", true), []), []), database(table('Q, primaryKey('Id), [], []) table('strings, primaryKey('Id), column('value, DB-STRING, []), foreignKey('Q, 'Q, NOTNULL)), []))) .
red test(addClass(class('Q, [],  primitiveCollection('strings, APP-STRING, "value", true) primitiveCollection('stringos, APP-STRING, "value", true), []), system(application([], []), database([],[]) )) == system(application(class('Q, [], primitiveCollection('strings, APP-STRING, "value", true) primitiveCollection('stringos, APP-STRING, "value", true), []), []), database(table('Q, primaryKey('Id), [], []) table('strings, primaryKey('Id), column('value, DB-STRING, []), foreignKey('Q, 'Q, NOTNULL)) table('stringos, primaryKey('Id), column('value, DB-STRING, []), foreignKey('Q, 'Q, NOTNULL)), []))) .
--- with properties
red test(addClass(class('Q, property('p, APP-STRING, "val", 1), [], []), system(application([], []), database([],[]) )) == system(application(class('Q, property('p, APP-STRING, "val", 1), [], []), []), database(table('Q, primaryKey('Id), column('p, DB-STRING, NOTNULL), []), []))) .
red test(addClass(class('Q, property('p, APP-STRING, "val", 1) property('pa, APP-STRING, "val", 0), [], []), system(application([], []), database([],[]) )) == system(application(class('Q, property('p, APP-STRING, "val", 1) property('pa, APP-STRING, "val", 0), [], []), []), database(table('Q, primaryKey('Id), column('p, DB-STRING, NOTNULL) column('pa, DB-STRING, []), []), []))) .
--- 1 : N
red test(addClass(class('C, [], [], association('Ref, 'Q, 1, 1)), system(application(class('Q, [], primitiveCollection('strings, APP-STRING, "value", true) primitiveCollection('stringos, APP-STRING, "value", true), []), []), database(table('Q, primaryKey('Id), [], []) table('strings, primaryKey('Id), column('value, DB-STRING, []), foreignKey('Q, 'Q, NOTNULL)) table('stringos, primaryKey('Id), column('value, DB-STRING, []), foreignKey('Q, 'Q, NOTNULL)), [])) ) == system(application(class('Q, [], primitiveCollection('strings, APP-STRING, "value", true) primitiveCollection('stringos, APP-STRING, "value", true), []) class('C, [], [], association('Ref, 'Q, 1, 1)), []), database(table('strings, primaryKey('Id), column('value, DB-STRING, []), foreignKey('Q, 'Q, NOTNULL)) table('stringos, primaryKey('Id), column('value, DB-STRING, []), foreignKey('Q, 'Q, NOTNULL)) table('C,primaryKey('Id), [], []) table('Q, primaryKey('Id), [], foreignKey('Ref,'C, NOTNULL)), []))).
--- M : N
red test(addClass(class('C, [], [], association('Ref, 'Q, 4, 1)), system(application(class('Q, [], [], []), []), database(table('Q,    primaryKey('Id), [], []), []))) == system(application(class('Q, [], [], []) class('C, [], [], association('Ref, 'Q, 4, 1)), []), database(table('Q, primaryKey('Id), [], []) table('C, primaryKey('Id), [], []) table('Ref, primaryKey('Id'), [], foreignKey('C, 'C, NOTNULL) foreignKey('Ref, 'Ref, NOTNULL)), []))) .
