load ../evoluce/evolution.maude
load ./colored_result.maude

fmod TESTSUITE is
	pr COLORING .
	pr ORM-SYSTEM .
endfm

--- ADDCLASS : Class OrmSystem -> OrmSystem .
red test(addClass(class('Q, [], []), system(application([], []), database([],[]) )) == system(application(class('Q, [], []), []), database(table('Q, primaryKey('Id), [], []), []))) .
red test(addClass(class('Q, [], []), system(application(class('Q, [], []), []), database([],[]) )) == system(errApplication("add class - the name already exists", application(class('Q, [], []), [])), database(table('Q, primaryKey('Id), [], []), []))) .
red test(addClass(class('Q, [], []), system(application([], []), database(table('Q, primaryKey('Id), [], []), []))) == system(application(class('Q, [], []), []), errDatabase("add table - name exists", database(table('Q, primaryKey('Id), [], []), [])))) .
--- with primitiveCollections
red test(addClass(class('Q, property('strings, APP-STRING, "value", 4), []), system(application([], []), database([],[]) )) == system(application(class('Q, property('strings, APP-STRING, "value", 4), []), []), database(table('Q, primaryKey('Id), [], []) table('strings, primaryKey('Id), column('value, DB-STRING, []), foreignKey('Q, 'Q, NOTNULL)), []))) .
red test(addClass(class('Q, property('strings, APP-STRING, "value", 5) property('stringos, APP-STRING, "value", 5), []), system(application([], []), database([],[]) )) == system(application(class('Q, property('strings, APP-STRING, "value", 5) property('stringos, APP-STRING, "value", 5), []), []), database(table('Q, primaryKey('Id), [], []) table('strings, primaryKey('Id), column('value, DB-STRING, []), foreignKey('Q, 'Q, NOTNULL)) table('stringos, primaryKey('Id), column('value, DB-STRING, []), foreignKey('Q, 'Q, NOTNULL)), []))) .
--- with singlePropertyList
red test(addClass(class('Q, property('p, APP-STRING, "val", 1), []), system(application([], []), database([],[]) )) == system(application(class('Q, property('p, APP-STRING, "val", 1), []), []), database(table('Q, primaryKey('Id), column('p, DB-STRING, NOTNULL), []), []))) .
red test(addClass(class('Q, property('p, APP-STRING, "val", 1) property('pa, APP-STRING, "val", 0), []), system(application([], []), database([],[]) )) == system(application(class('Q, property('p, APP-STRING, "val", 1) property('pa, APP-STRING, "val", 0), []), []), database(table('Q, primaryKey('Id), column('p, DB-STRING, NOTNULL) column('pa, DB-STRING, []), []), []))) .
red test(addClass(class('Q, property('p, APP-STRING, "val", 1) property('q, APP-STRING, "va", 5), []), system(application([], []), database([], []))) == system(application(class('Q, property('p, APP-STRING, "val", 1) property('q, APP-STRING, "va", 5), []), []), database(table('Q, primaryKey('Id), column('p, DB-STRING, NOTNULL), []) table('q, primaryKey('Id), column('value, DB-STRING, []), foreignKey('Q, 'Q, NOTNULL)), []))) . 
--- 1 : N
red test(addClass(class('C, [], association('Ref, 'Q, 1, 1)), system(application(class('Q, property('strings, APP-STRING, "value", 5) property('stringos, APP-STRING, "value", 5), []), []), database(table('Q, primaryKey('Id), [], []) table('strings, primaryKey('Id), column('value, DB-STRING, []), foreignKey('Q, 'Q, NOTNULL)) table('stringos, primaryKey('Id), column('value, DB-STRING, []), foreignKey('Q, 'Q, NOTNULL)), [])) ) == system(application(class('Q, property('strings, APP-STRING, "value", 5) property('stringos, APP-STRING, "value", 5), []) class('C, [], association('Ref, 'Q, 1, 1)), []), database(table('strings, primaryKey('Id), column('value, DB-STRING, []), foreignKey('Q, 'Q, NOTNULL)) table('stringos, primaryKey('Id), column('value, DB-STRING, []), foreignKey('Q, 'Q, NOTNULL)) table('C,primaryKey('Id), [], []) table('Q, primaryKey('Id), [], foreignKey('Ref,'C, NOTNULL)), []))).
--- M : N
red test(addClass(class('C, [], association('Ref, 'Q, 4, 1)), system(application(class('Q, [], []), []), database(table('Q,    primaryKey('Id), [], []), []))) == system(application(class('Q, [], []) class('C, [], association('Ref, 'Q, 4, 1)), []), database(table('Q, primaryKey('Id), [], []) table('C, primaryKey('Id), [], []) table('Ref, primaryKey('Id'), [], foreignKey('C, 'C, NOTNULL) foreignKey('Ref, 'Ref, NOTNULL)), []))) .



