load ../evoluce/evolution.maude
load ./colored_result.maude

fmod TESTSUITE is
	pr COLORING .
	pr ORMSYSTEM .
endfm

--- Property to Column Tests
red test(prop2col(property('surname, APP-STRING, "value", false)) == column('surname, DB-STRING, [])) .
red test(prop2col(property('surname, APP-STRING, "value", true)) == column('surname, DB-STRING, NOTNULL)) .


--- List{Property} tp List{Column} Tests
red test(props2cols([]) == []) .
red test(props2cols(property('surname, APP-STRING, "value", false)) == column('surname, DB-STRING, [])) .
red test(props2cols(property('surname, APP-STRING, "value", false) property('firstName, APP-STRING, "value", true)) == column('surname, DB-STRING, []) column('firstName, DB-STRING, NOTNULL)) .

--- Collection to Table Tests
red test(collection2table('className, primitiveCollection('strings, APP-STRING, "value", true)) == table('strings, primaryKey('Id), column('value, DB-STRING, []), foreignKey('className, 'className, NOTNULL))) .
red test(collections2tables('className, primitiveCollection('strings, APP-STRING, "value", true) primitiveCollection('stringos, APP-STRING, "value", true)) == table('strings, primaryKey('Id), column('value, DB-STRING,
    []), foreignKey('className, 'className, NOTNULL)) table('stringos, primaryKey('Id), column('value, DB-STRING, []), foreignKey('className,'className, NOTNULL))) .

--- Collection to Tables Tests
red test(collections2tables('Q, primitiveCollection('strings, APP-STRING, "value", true)) == table('strings, primaryKey('Id), column('value, DB-STRING, []), foreignKey('Q, 'Q, NOTNULL))) .
red test(collections2tables('Q, primitiveCollection('strings, APP-STRING, "value", true) primitiveCollection('stringos, APP-STRING, "value", true)) == table('strings, primaryKey('Id), column('value, DB-STRING, []), foreignKey('Q, 'Q, NOTNULL)) table('stringos, primaryKey('Id), column('value, DB-STRING, []), foreignKey('Q, 'Q, NOTNULL))) .

--- AddTables
red test(addTables(table('strings, primaryKey('Id), column('value, DB-STRING, []), foreignKey('Q, 'Q, NOTNULL)) table('stringos, primaryKey('Id), column('value, DB-STRING, []), foreignKey('Q, 'Q, NOTNULL)), database([],[])) == errDatabase("add table - reference(s) not exist(s)", database([], []))) .
red test(addTables(table('Q, primaryKey('Id), column('value, DB-STRING, []), []) table('stringos, primaryKey('Id), column('value, DB-STRING, []), foreignKey('Q, 'Q, NOTNULL)), database([],[])) == database(table('Q, primaryKey('Id), column('value, DB-STRING, []), []) table('stringos, primaryKey('Id), column('value, DB-STRING, []), foreignKey('Q, 'Q, NOTNULL)), [])) .
red test(addTables(table('strings, primaryKey('Id), column('value, DB-STRING, []), foreignKey('Q, 'Q, NOTNULL)) table('Q, primaryKey('Id), column('value, DB-STRING, []), []), database([],[])) == errDatabase("add table - reference(s) not exist(s)", database([], []))) .

--- < label, type, defaultValue, ordered, unique, upperBound, mandatory >
---red test(collection2table('className, primitiveCollection('strings, APP-STRING, "value", true, true, |*, true)) == ) .

--- addClass2Db property*, primitiveCollection*, association*
---red addClass2Db(class('class, [], [], [] ), database([], [])) .
